//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamWork.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskHistory
    {
        public int Id { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> EffectedUserId { get; set; }
        public string Description { get; set; }
        public string OldStatus { get; set; }
        public string NewStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
    }
}
